sudo: false
language: cpp
  - ci_host=i686-w64-mingw32
  - ci_host=i686-w64-mingw32 ci_buildsys=cmake ci_variant=debug
  - ci_host=x86_64-w64-mingw32 ci_variant=debug
  - ci_host=x86_64-w64-mingw32 ci_buildsys=cmake
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6
    - clang-3.8
    - gcc
    - gcc-mingw-w64
    - libc6-dev-i386
    - freeglut3-dev
    - libsdl1.2-dev
    - libsdl-image1.2-dev
    - libsdl-ttf2.0-dev
    - libsdl-gfx1.2-dev
    - libsdl-net1.2-dev
    - libboost-dev
    - libboost-all-dev
    - libopenal-dev
install:
- "[ $CXX = gcc-mingw-w64 ] && export CXX=gcc-mingw-w64 || true"
#- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
script:
  - cmake ./
  - make


  #download libSGE
  #- git clone https://github.com/flibitijibibo/libSGE
  #- git checkout 3facdc9
  #- cd libSGE && sudo make install
